name: flutter_load_save_image
description: "Example Flutter Code for loading and saving local images."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.0.0-417.0.dev

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image:  ^4.0.15
  image_picker: ^1.0.4
  permission_handler: ^10.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
